---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: gitopsrvc-appstudio-shared
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: namespaces
  - group: managed-gitops.redhat.com
    identityHash: ca9eb24baa2a9a49abae385916aa4ad61698e05d49ac9dddd485710c2f968775
    resource: gitopsdeployments
  - group: appstudio.redhat.com
    identityHash: 5dea7127190b3f8e358ff920e09c380d8cdb011bc79fc5325f103fa068160cf8
    resource: applications
  - group: appstudio.redhat.com
    identityHash: 5dea7127190b3f8e358ff920e09c380d8cdb011bc79fc5325f103fa068160cf8
    resource: applicationsnapshotenvironmentbindings
  - group: appstudio.redhat.com
    identityHash: 5dea7127190b3f8e358ff920e09c380d8cdb011bc79fc5325f103fa068160cf8
    resource: components
  - group: appstudio.redhat.com
    identityHash: 5dea7127190b3f8e358ff920e09c380d8cdb011bc79fc5325f103fa068160cf8
    resource: environments
