---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/stuartwdouglas/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-add-topology-spread-constraint
