---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: jvm-build-service
  namespace: jvm-build-service
spec:
  latestResourceSchemas:
  - v202210180116.artifactbuilds.jvmbuildservice.io
  - v202210180116.dependencybuilds.jvmbuildservice.io
  - v202210180116.rebuiltartifacts.jvmbuildservice.io
  - v202210180116.systemconfigs.jvmbuildservice.io
  - v202210180116.tektonwrappers.jvmbuildservice.io
  - v202210180116.userconfigs.jvmbuildservice.io
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: configmaps
  - group: ""
    resource: events
  - group: ""
    resource: resourcequotas
  - group: tekton.dev
    identityHash: 3ea06bce2bddb089abb8a1278bee32708909e34f73c558f0aef362c6163b3362
    resource: pipelineruns
