resources:
- allow-argocd-to-manage.yaml
- https://github.com/mmorhun/image-controller/config/default?ref=84003489deb6f9124f6b050f5a34c59027db1f08

images:
- name: quay.io/redhat-appstudio/image-controller
  # newName: quay.io/redhat-appstudio/image-controller
  # newTag: 843b52f
  # Using image from the build itself, because of the problems with the release flow.
  newName: quay.io/redhat-user-workloads/rhtap-build-tenant/build/image-controller
  newTag: on-pr-84003489deb6f9124f6b050f5a34c59027db1f08

namespace: image-controller

patches:
  - path: ./manager_resources_patch.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

