---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: build-service
  namespace: build-service
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: configmaps
  - group: ""
    resource: namespaces
  - group: ""
    resource: events
  - group: ""
    resource: serviceaccounts
  - group: tekton.dev
    identityHash: e3ff165ded9505c09246758a1992860804870006211636806276d63e528da1e7
    resource: pipelineruns
  - group: appstudio.redhat.com
    identityHash: 5dea7127190b3f8e358ff920e09c380d8cdb011bc79fc5325f103fa068160cf8
    resource: components
  - group: appstudio.redhat.com
    identityHash: 5dea7127190b3f8e358ff920e09c380d8cdb011bc79fc5325f103fa068160cf8
    resource: applications
  - group: appstudio.redhat.com
    identityHash: 5dea7127190b3f8e358ff920e09c380d8cdb011bc79fc5325f103fa068160cf8
    resource: applicationsnapshots
